function(appicon TARGET_NAME ICON_FILE RESOURCE_FILES)
    if(WIN32)
        set(ICON_RESOURCE "${ICON_FILE}")
        set(RC_CONTENT "IDI_ICON1    ICON    DISCARDABLE     \"${ICON_FILE}\"")
        set(RC_FILE ${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}.rc)
        file(WRITE ${RC_FILE} "${RC_CONTENT}")
        set(RESOURCE_FILES ${ICON_RESOURCE} ${TARGET_NAME}.rc PARENT_SCOPE)
    elseif(APPLE)
        get_filename_component(ICON_FILE_NAME ${ICON_FILE} NAME)
        set(MACOSX_BUNDLE_ICON_FILE ${ICON_FILE_NAME})
        set_source_files_properties(${ICON_FILE} PROPERTIES MACOSX_PACKAGE_LOCATION "Resources")
        set(RESOURCE_FILES ${ICON_FILE} PARENT_SCOPE)
    elseif(UNIX AND NOT APPLE)
        set(ICON_RESOURCE "${ICON_FILE}")
        set(DESKTOP_CONTENT "[Desktop Entry]\n Type=Application\n  Icon")
        # install(FILES ${ICON_FILE} DESTINATION ${CMAKE_INSTALL_PREFIX}/share/icons/hicolor/48x48/apps/)
    endif()
endfunction()