name: ci-macos

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]


  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: macos-latest
    timeout-minutes: 120

    strategy:
      matrix:
        build_type: [Release]
        c_compiler: [clang]
        cpp_compiler: [clang++]
        qt: [5.15.2]
        qt_modules: [qtpdf qtimageformats]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Init Submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive

      - name: Install Dependencies
        run: |
          brew install tree

      - name: Install macdeployqtfix
        run: |
          git clone https://github.com/tamlok/macdeployqtfix.git macdeployqtfix --depth=1
        working-directory: ${{runner.workspace}}

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1  # not v2!
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache-${{ matrix.qt }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt }}
          target: desktop
          modules:  ${{ matrix.qt_modules }}
          cached: 'true'
          setup-python: 'false'

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name:  Build Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target all --
        
      - name:  Install Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target install --

      # when stable to test
      # - name: Test
      #   working-directory: ${{ github.workspace }}/build
      #   run: ctest --build-config ${{ matrix.build_type }}
