name: ci-macos

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]


  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    name: Build On Macos
    runs-on: macos-13
    timeout-minutes: 120

    strategy:
      matrix:
        build_type: [Release]
        install_path: [installed]
        c_compiler: [clang]
        cpp_compiler: [clang++]
        qt: [5.15.2]
        qt_modules: [qtwebengine]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ github.workspace }}/ThirdParty/vcpkg'
          vcpkgJsonGlob: '${{ github.workspace }}/vcpkg-configuration.json'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt }}
          host: 'mac'
          target: desktop
          modules:  ${{ matrix.qt_modules }}
          cache: 'true'
          setup-python: 'false'

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_INSTALL_PREFIX=${{ matrix.install_path }}
          -S ${{ github.workspace }}

      - name:  Build Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --parallel --target all --
        
      - name:  Install Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target install --

      # when stable to test
      # - name: Test
      #   working-directory: ${{ github.workspace }}/build
      #   run: ctest --build-config ${{ matrix.build_type }}
