name: ci-release

on:
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Required for creating GitHub release.
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  product_name: sVanilla
  qt_version: 6.7.1
  qt_modules: qtwebengine qtwebchannel qtpositioning qtpdf qtimageformats qt5compat qtserialport

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-2022
    timeout-minutes: 120

    strategy:
      matrix:
        build_type: [Release]
        install_path: [package/installed]
        asset_path: [package/asset]
        c_compiler: [cl]
        cpp_compiler: [cl]
        arch: [win64_msvc2019_64]
        platform: [x64]

    steps:
      - name: Get clone
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Get cmake 
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.31.8

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ github.workspace }}/ThirdParty/vcpkg'

      - name: Install Qt Official Build
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_version }}
          target: desktop
          arch: ${{matrix.arch}}
          modules: ${{env.qt_modules}}
          cache: 'true'

      - name: Install dependencies
        run: |
          pip install virtualenv

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_INSTALL_PREFIX=${{ matrix.install_path }}
          -DENABLE_BUILD_PLUGINS=ON
          -DGIT_BRANCH=${{ github.ref_name }}
          -S ${{ github.workspace }}

      - name: Extract CMake Project Version
        run: |
          $BuildDir = "${{ github.workspace }}\build"
          $Output = cmake -L -N $BuildDir | Select-String -Pattern "CMAKE_PROJECT_VERSION_STR"
          if (-not $Output) {
              Write-Error "Error: Unable to retrieve CMAKE_PROJECT_VERSION_STR."
              exit 1
          }
          $Version = ($Output -split "=")[1].Trim()
          echo "VERSION=$Version" >> $env:GITHUB_ENV

      - name:  Build Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --parallel --target all_build --
        
      - name:  Install Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target install --

      - name: Get current date
        id: date
        run: |
          $branchName = "${{ github.ref }}" -replace '^refs/tags/', ''
          if ($branchName -match '^v\d+\.\d+\.\d+$') {
            echo "ref_id=$branchName" >> $env:GITHUB_ENV
          } else {
            echo "ref_id=$(Get-Date -Format 'yyyy-MM-dd')" >> $env:GITHUB_ENV
          }

      - name:  collect pdb
        run: python.exe scripts/collection_pdb.py -b ${{ github.workspace }}/build -o ${{ matrix.asset_path }}/${{ env.product_name }}_${{ env.ref_id}}_pdb.zip

      - name: Zip Package
        run: |
          Get-ChildItem -Path "${{ matrix.install_path }}/bin/*" -Recurse -Filter "*.pdb" | Remove-Item -Force
          if (-Not (Test-Path ${{ matrix.asset_path }})) {
              New-Item -Path ${{ matrix.asset_path }} -ItemType Directory
          }
          Compress-Archive -Path ${{ matrix.install_path }}/bin/* -DestinationPath ${{ matrix.asset_path }}/${{ env.product_name }}_${{ env.ref_id}}_win64_portable.zip

      - name: Create .msi package
        id: create_msi
        run: |
          python.exe scripts/generator_install_manifest.py -d ${{ matrix.install_path }}/bin/ -o ${{ matrix.install_path }}/bin/manifest.json
          python.exe scripts/generator_wxs.py -i ${{ matrix.install_path }}/bin/
          candle.exe -nologo -out installer/ build/${{ env.product_name }}.wxs scripts/wix/ui.wxs
          light.exe -nologo -out ${{ matrix.asset_path }}/${{ env.product_name }}_${{ env.ref_id}}_win64_installer.msi installer/${{ env.product_name }}.wixobj installer/ui.wixobj  -ext WixUIExtension
          Remove-Item -Path "${{ matrix.asset_path }}/${{ env.product_name }}_${{ env.ref_id}}_win64_installer.wixpdb" -Force

      - name: Install Inno Setup
        run: choco install innosetup --no-progress -y

      - name: create .EXE Installer
        id: create_exe_installer
        run: >
          iscc scripts/inno_setup/installer.iss
          /DRootPath=${{ github.workspace }}/${{ matrix.install_path }}/bin
          /DCurrenData=${{ env.ref_id}}
          /DMyAppVersion=${{ env.VERSION}}
          /O${{ github.workspace }}/${{ matrix.asset_path }}
      
      - name: Archive build logs on failure
        if: ${{ failure() && (steps.create_msi.outcome == 'failure' || steps.create_exe_installer.outcome == 'failure') }}
        run: |
          Compress-Archive -Path "${{ github.workspace }}/build" -DestinationPath "${{ github.workspace }}/build.zip" -Force
          Compress-Archive -Path "${{ github.workspace }}/ThirdParty/vcpkg/buildtrees/" -DestinationPath "${{ github.workspace }}/vcpkg.zip" -Force
          Compress-Archive -Path "${{ github.workspace }}/${{ matrix.install_path }}/bin" -DestinationPath "${{ github.workspace }}/output.zip" -Force

      - name: Upload build logs artifact
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: windows_release_logs
          path: |
            ${{ github.workspace }}/build.zip
            ${{ github.workspace }}/output.zip
            ${{ github.workspace }}/vcpkg.zip 

      - name: Calculate SHA256 checksums for each file
        run: |
          $Files = Get-ChildItem -File -Path "${{ matrix.asset_path }}/*"
          foreach ($File in $Files) {
              $Hash = Get-FileHash $File.FullName -Algorithm SHA256
              $HashFile = "${{ matrix.asset_path }}/$($File.Name).sha256"
              "$($Hash.Hash) *$($File.Name)" | Out-File -FilePath $HashFile
          }

      - name: Update GitHub Release
        uses: actions/upload-artifact@v6
        with:
          name: windows
          path: |
            ${{ matrix.asset_path }}/*.zip
            ${{ matrix.asset_path }}/*.sha256
            ${{ matrix.asset_path }}/*.msi
            ${{ matrix.asset_path }}/*.exe

      - name: Upload Release Assets
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          $files = Get-ChildItem -Path ${{ matrix.asset_path }}/*;
          foreach ($file in $files) {
            Write-Output "Uploading $file"
            gh release upload ${{ github.ref_name }} "$($file.FullName)" --clobber
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    name: build-linux
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    strategy:
      matrix:
        build_type: [Release]
        install_path: [package/installed]
        asset_path: [package/asset]
        temp_path: [package/temp_dir]
        c_compiler: [gcc]
        cpp_compiler: [g++]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.31.8

      - name: Install Dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libfcitx5-qt-dev tree

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ github.workspace }}/ThirdParty/vcpkg'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_version }}
          target: desktop
          modules: ${{ env.qt_modules }}
          cache: 'true'

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_INSTALL_PREFIX=${{ matrix.install_path }}
          -DENABLE_BUILD_PLUGINS=ON
          -DGIT_BRANCH=${{ github.ref_name }}
          -S ${{ github.workspace }}

      - name:  Build Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --parallel --target all --
        
      - name:  Install Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target install --

      - name: Get current date
        id: date
        run: |
          branchName="${GITHUB_REF#refs/tags/}"
          if [[ "$branchName" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "ref_id=$branchName" >> $GITHUB_ENV
          else
            echo "ref_id=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          fi

      - name: 'Install dependencies'
        run: |
          sudo apt-get update
          sudo apt install desktop-file-utils libfuse2 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-composite0 libxcb-cursor0 libxcb-damage0 libxcb-dpms0 libxcb-dri2-0 libxcb-dri3-0 libxcb-ewmh2 libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-record0 libxcb-render0 libxcb-res0 libxcb-screensaver0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 libxkbcommon-x11-0

      - name: tar  Package
        run: |
          mkdir -p ${{ matrix.temp_path }}
          cp -r ${{ matrix.install_path }}/bin/.  ${{ matrix.temp_path }}
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt-continuous-x86_64.AppImage
          export LD_LIBRARY_PATH=${{ github.workspace }}/build/vcpkg_installed/x64-linux/lib:${{ github.workspace }}/${{ matrix.install_path }}/bin:${{ github.workspace }}/${{ matrix.install_path }}/bin/ffmpeg:$LD_LIBRARY_PATH
          ./linuxdeployqt-continuous-x86_64.AppImage ${{ github.workspace }}/${{ matrix.temp_path }}/${{ env.product_name }} -always-overwrite -no-translations -unsupported-allow-new-glibc
          rm linuxdeployqt-continuous-x86_64.AppImage
          find ${{ matrix.temp_path }} -type f ! -name "*.*" -exec chmod +x {} \;
          mkdir -p ${{ matrix.asset_path }}
          tar -czvf ${{ matrix.asset_path }}/${{ env.product_name }}_${{ env.ref_id}}_x86_64_linux.tar.gz -C ${{ matrix.temp_path }} .
          
      - name: 'Install linuxdeploy'
        run: |
          pwd
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy-plugin-appimage-x86_64.AppImage

      - name: 'Create AppImage'
        id: create_appimage
        run: |
          python scripts/generator_install_manifest.py -d ${{ matrix.install_path }}/bin/ -o ${{ matrix.install_path }}/${{ env.product_name }}/usr/bin/manifest.json
          cp -r ${{ matrix.install_path }}/bin/plugin ${{ matrix.install_path }}/${{ env.product_name }}/usr/bin/
          find ${{ matrix.install_path }}/${{ env.product_name }}/usr/bin/ -type f ! -name "*.*" -exec chmod +x {} \;
          sed -i 's|^Exec=.*|Exec=sVanilla|' ${{ matrix.install_path }}/bin/share/applications/sVanilla.desktop
          export LD_LIBRARY_PATH=${{ github.workspace }}/build/vcpkg_installed/x64-linux/lib:${{ github.workspace }}/${{ matrix.install_path }}/bin:${{ github.workspace }}/${{ matrix.install_path }}/bin/ffmpeg:$LD_LIBRARY_PATH
          ./linuxdeploy-x86_64.AppImage --appdir ${{ matrix.install_path }}/${{ env.product_name }} -e ${{ matrix.install_path }}/bin/${{ env.product_name }} -i ${{ matrix.install_path }}/bin/share/icon/sVanilla.svg -d ${{ matrix.install_path }}/bin/share/applications/sVanilla.desktop --plugin qt --output appimage --custom-apprun ${{ github.workspace }}/cmake/AppRun
          rm linuxdeploy-x86_64.AppImage
          rm linuxdeploy-plugin-qt-x86_64.AppImage
          rm linuxdeploy-plugin-appimage-x86_64.AppImage
          mv *.AppImage ${{ matrix.asset_path }}/${{ env.product_name }}_${{ env.ref_id }}-x86_64.AppImage ||:
      
      - name: Archive build logs on failure
        if: ${{ failure() && steps.create_appimage.outcome == 'failure' }}
        run: |
          tar -czvf ${{ github.workspace }}/build.tar.gz -C ${{ github.workspace }}/build/ .
          tar -czvf ${{ github.workspace }}/vcpkg.tar.gz -C ${{ github.workspace }}/ThirdParty/vcpkg/buildtrees/ .
          tar -czvf ${{ github.workspace }}/output.tar.gz -C ${{ matrix.install_path }}/bin/ .

      - name: Upload build logs artifact
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: linux_release_logs
          path: |
            ${{ github.workspace }}/build.tar.gz
            ${{ github.workspace }}/output.tar.gz
            ${{ github.workspace }}/vcpkg.tar.gz 
          
      - name: Calculate SHA256 checksums for each file
        run: |
          cd  "${{ matrix.asset_path }}" || exit
          for file in *; do
              [ -f "$file" ] && sha256sum "$file" > "$file.sha256"
          done

      - name: Update GitHub Release
        uses: actions/upload-artifact@v6
        with:
          name: linux
          path: |
            ${{ matrix.asset_path }}/*.AppImage
            ${{ matrix.asset_path }}/*.sha256
            ${{ matrix.asset_path }}/*.tar.gz

      - name: Upload Release Assets
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          files=$(find ${{ matrix.asset_path }} -type f);
          for file in $files; do
            echo "Uploading $file"
            gh release upload "${{ github.ref_name }}" "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
      name: build-macos
      runs-on: macos-15-intel
      timeout-minutes: 120

      strategy:
        matrix:
          build_type: [Release]
          install_path: [package/installed]
          asset_path: [package/asset]
          c_compiler: [clang]
          cpp_compiler: [clang++]

      steps:
        - uses: actions/checkout@v5
          with:
            submodules: recursive
            fetch-depth: 0

        - uses: lukka/get-cmake@latest
          with:
            cmakeVersion: 3.31.8

        - name: Setup Python venv (global)
          run: |
            python3 -m venv .venv
            echo "VIRTUAL_ENV=${{ github.workspace }}/.venv" >> $GITHUB_ENV
            echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

        - name: Setup vcpkg
          uses: lukka/run-vcpkg@v11
          id: runvcpkg
          with:
            vcpkgDirectory: '${{ github.workspace }}/ThirdParty/vcpkg'

        - name: Install Qt
          uses: jurplel/install-qt-action@v4
          with:
            version: ${{ env.qt_version }}
            host: 'mac'
            target: desktop
            modules:  ${{ env.qt_modules }}
            cache: 'true'
            setup-python: 'false'

        - name: Configure CMake
          run: >
            cmake -B ${{ github.workspace }}/build
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
            -DCMAKE_INSTALL_PREFIX=${{ matrix.install_path }}
            -DENABLE_BUILD_PLUGINS=ON
            -DGIT_BRANCH=${{ github.ref_name }}
            -S ${{ github.workspace }}

        - name:  Build Project
          run: |
            export Qt6_DIR=${QT_ROOT_DIR}/lib
            cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --parallel --target all --
          
        - name:  Install Project
          run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target install --

        - name: Get current date
          id: date
          run: |
            branchName="${GITHUB_REF#refs/tags/}"
            if [[ "$branchName" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "ref_id=$branchName" >> $GITHUB_ENV
            else
              echo "ref_id=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
            fi

        - name: tar  Package
          run: |
            chmod +x scripts/packageosx.sh
            scripts/packageosx.sh ${{ matrix.install_path }}/sVanilla.app ${{ github.workspace }}/${{ matrix.install_path }}/bin/
            find ${{ matrix.install_path }}/ -type f ! -name "*.*" -exec chmod +x {} \;
            mkdir -p ${{ matrix.asset_path }}
            tar -czvf ${{ matrix.asset_path }}/${{ env.product_name }}_${{ env.ref_id}}_x86_64_mac.tar.gz -C ${{ matrix.install_path }}/bin .

        - name: 'Create dmg'
          id: create_dmg
          run: |
            python scripts/generator_install_manifest.py -d ${{ matrix.install_path }}/sVanilla.app/Contents/MacOS -o ${{ matrix.install_path }}/sVanilla.app/Contents/MacOS/manifest.json
            hdiutil detach "/Volumes/sVanilla" || true
            rm -f ${{ matrix.install_path }}/*.dmg
            find ${{ matrix.install_path }}/ -type f ! -name "*.*" -exec chmod +x {} \;
            macdeployqt ${{ matrix.install_path }}/sVanilla.app -dmg
            mv ${{ matrix.install_path }}/*.dmg ${{ matrix.asset_path }}/${{ env.product_name }}_${{ env.ref_id }}_x86_64.dmg

        - name: Archive build logs on failure
          if: ${{ failure() && steps.create_dmg.outcome == 'failure' }}
          run: |
            tar -czvf ${{ github.workspace }}/build.tar.gz -C ${{ github.workspace }}/build/ .
            tar -czvf ${{ github.workspace }}/vcpkg.tar.gz -C ${{ github.workspace }}/ThirdParty/vcpkg/buildtrees/ .
            tar -czvf ${{ github.workspace }}/output.tar.gz -C ${{ matrix.install_path }}/bin .

        - name: Upload build logs artifact
          if: failure()
          uses: actions/upload-artifact@v6
          with:
            name: macos_release_logs
            path: |
              ${{ github.workspace }}/build.tar.gz
              ${{ github.workspace }}/output.tar.gz
              ${{ github.workspace }}/vcpkg.tar.gz 
                
        - name: Calculate SHA256 checksums for each file
          run: |
            cd "${{ matrix.asset_path }}" || exit
            for file in *; do
              if [ -f "$file" ]; then
                  shasum -a 256 "$file" > "$file.sha256"
              fi
            done

        - name: Update GitHub Release
          uses: actions/upload-artifact@v6
          with:
            name: macos
            path: |
              ${{ matrix.asset_path }}/*.dmg
              ${{ matrix.asset_path }}/*.sha256
              ${{ matrix.asset_path }}/*.tar.gz

        - name: Upload Release Assets
          if: ${{ startsWith(github.ref, 'refs/tags/') }}
          run: |
            files=$(find ${{ matrix.asset_path }} -type f);
            for file in $files; do
              echo "Uploading $file"
              gh release upload "${{ github.ref_name }}" "$file" --clobber
            done
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos-arm:
        name: build-macos-arm
        runs-on: macos-15
        timeout-minutes: 120

        strategy:
          matrix:
            build_type: [Release]
            install_path: [package/installed]
            asset_path: [package/asset]
            c_compiler: [clang]
            cpp_compiler: [clang++]

        steps:
          - uses: actions/checkout@v5
            with:
              submodules: recursive
              fetch-depth: 0

          - uses: lukka/get-cmake@latest
            with:
              cmakeVersion: 3.31.8

          - name: Set up virtualenv and inject PATH
            run: |
              python -m venv venv
              echo "PATH=$(pwd)/venv/bin:$PATH" >> $GITHUB_ENV

          - name: Setup vcpkg
            uses: lukka/run-vcpkg@v11
            id: runvcpkg
            with:
              vcpkgDirectory: '${{ github.workspace }}/ThirdParty/vcpkg'

          - name: Install Qt
            uses: jurplel/install-qt-action@v4
            with:
              version: ${{ env.qt_version }}
              host: 'mac'
              target: desktop
              modules:  ${{ env.qt_modules }}
              cache: 'true'
              setup-python: 'false'

          - name: Configure CMake
            run: >
              cmake -B ${{ github.workspace }}/build
              -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
              -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
              -DCMAKE_INSTALL_PREFIX=${{ matrix.install_path }}
              -DENABLE_BUILD_PLUGINS=ON
              -DGIT_BRANCH=${{ github.ref_name }}
              -S ${{ github.workspace }}

          - name:  Build Project
            run: |
              export Qt6_DIR=${QT_ROOT_DIR}/lib
              cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --parallel --target all --
            
          - name:  Install Project
            run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target install --

          - name: Get current date
            id: date
            run: |
              branchName="${GITHUB_REF#refs/tags/}"
              if [[ "$branchName" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                echo "ref_id=$branchName" >> $GITHUB_ENV
              else
                echo "ref_id=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
              fi

          - name: tar  Package
            run: |
              chmod +x scripts/packageosx.sh
              scripts/packageosx.sh ${{ matrix.install_path }}/sVanilla.app ${{ github.workspace }}/${{ matrix.install_path }}/bin/
              find ${{ matrix.install_path }}/ -type f ! -name "*.*" -exec chmod +x {} \;
              mkdir -p ${{ matrix.asset_path }}
              tar -czvf ${{ matrix.asset_path }}/${{ env.product_name }}_${{ env.ref_id}}_arm_mac.tar.gz -C ${{ matrix.install_path }}/bin .

          - name: 'Create dmg'
            id: create_dmg
            run: |
              python scripts/generator_install_manifest.py -d ${{ matrix.install_path }}/sVanilla.app/Contents/MacOS -o ${{ matrix.install_path }}/sVanilla.app/Contents/MacOS/manifest.json
              hdiutil detach "/Volumes/sVanilla" || true
              rm -f ${{ matrix.install_path }}/*.dmg
              find ${{ matrix.install_path }}/ -type f ! -name "*.*" -exec chmod +x {} \;
              macdeployqt ${{ matrix.install_path }}/sVanilla.app -dmg
              mv ${{ matrix.install_path }}/*.dmg ${{ matrix.asset_path }}/${{ env.product_name }}_${{ env.ref_id }}_arm.dmg

          - name: Archive build logs on failure
            if: ${{ failure() && steps.create_dmg.outcome == 'failure' }}
            run: |
              tar -czvf ${{ github.workspace }}/build.tar.gz -C ${{ github.workspace }}/build/ .
              tar -czvf ${{ github.workspace }}/vcpkg.tar.gz -C ${{ github.workspace }}/ThirdParty/vcpkg/buildtrees/ .
              tar -czvf ${{ github.workspace }}/output.tar.gz -C ${{ matrix.install_path }}/bin .

          - name: Upload build logs artifact
            if: failure()
            uses: actions/upload-artifact@v6
            with:
              name: macos_release_logs
              path: |
                ${{ github.workspace }}/build.tar.gz
                ${{ github.workspace }}/output.tar.gz
                ${{ github.workspace }}/vcpkg.tar.gz 
                  
          - name: Calculate SHA256 checksums for each file
            run: |
              cd "${{ matrix.asset_path }}" || exit
              for file in *; do
                if [ -f "$file" ]; then
                    shasum -a 256 "$file" > "$file.sha256"
                fi
              done

          - name: Update GitHub Release
            uses: actions/upload-artifact@v6
            with:
              name: macos_arm
              path: |
                ${{ matrix.asset_path }}/*.dmg
                ${{ matrix.asset_path }}/*.sha256
                ${{ matrix.asset_path }}/*.tar.gz

          - name: Upload Release Assets
            if: ${{ startsWith(github.ref, 'refs/tags/') }}
            run: |
              files=$(find ${{ matrix.asset_path }} -type f);
              for file in $files; do
                echo "Uploading $file"
                gh release upload "${{ github.ref_name }}" "$file" --clobber
              done
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

