name: ci-windows

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]


  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: windows-2019
    timeout-minutes: 120

    strategy:
      matrix:
        build_type: [Release]
        c_compiler: [cl]
        cpp_compiler: [cl]
        arch: [win64_msvc2019_64]
        platform: [x64]
        qt: [6.5.2]
        qt_modules: [qtwebengine qtwebchannel qtpositioning qtpdf qtimageformats qt5compat]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Init Submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1  # not v2!
        with:
          path: ../Qt
          key: ${{runner.os}}-${{matrix.arch}}-QtCache-${{matrix.qt}}

      - name: Install Qt Official Build
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{matrix.qt}}
          target: desktop
          arch: ${{matrix.arch}}
          modules: ${{matrix.qt_modules}}
          cache: 'true'

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name:  Build Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target sVanilla --
        
      - name:  Install Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target install --
        
      # when stable to test
      # - name: Test
      #   working-directory: ${{ github.workspace }}/build
      #   run: ctest --build-config ${{ matrix.build_type }}
